export default function Links(){
    
return(
    <>
        <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1 maximum-scale=1"
    />
    <link rel="profile" href="https://gmpg.org/xfn/11" />
    <script
      type="text/javascript"
      async=""
      src="https://www.google-analytics.com/analytics.js"
    ></script>
    {/* <script>
      document.documentElement.className =
        document.documentElement.className + " yes-js js_active js";
    </script> */}
    <meta name="robots" content="max-image-preview:large" />
    <link rel="dns-prefetch" href="//fonts.googleapis.com" />
    <link rel="dns-prefetch" href="//s.w.org" />
    <link href="https://fonts.gstatic.com" crossorigin="" rel="preconnect" />
    <link
      rel="alternate"
      type="application/rss+xml"
      title="Cartsy Furniture » Feed"
      href="https://cartsy.redq.io/furniture/feed/"
    />
    <link
      rel="alternate"
      type="application/rss+xml"
      title="Cartsy Furniture » Comments Feed"
      href="https://cartsy.redq.io/furniture/comments/feed/"
    />
    <script
      src="https://cartsy.redq.io/furniture/wp-includes/js/wp-emoji-release.min.js?ver=5.9"
      type="text/javascript"
      defer=""
    ></script>
    <link
      rel="stylesheet"
      id="wp-components-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-includes/css/dist/components/style.min.css?ver=5.9"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="wc-admin-payment-method-promotions-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/payment-method-promotions/style.css?ver=3.0.3-b-modified-1643516941"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="buttons-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-includes/css/buttons.min.css?ver=5.9"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="dashicons-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-includes/css/dashicons.min.css?ver=5.9"
      type="text/css"
      media="all"
    />
    
    <link
      rel="stylesheet"
      id="mediaelement-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-includes/js/mediaelement/mediaelementplayer-legacy.min.css?ver=4.2.16"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="wp-mediaelement-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-includes/js/mediaelement/wp-mediaelement.min.css?ver=5.9"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="media-views-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-includes/css/media-views.min.css?ver=5.9"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="imgareaselect-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-includes/js/imgareaselect/imgareaselect.css?ver=0.9.8"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="wp-block-library-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-includes/css/dist/block-library/style.min.css?ver=5.9"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="wc-blocks-vendors-style-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks-vendors-style.css?ver=6.5.2-b-modified-1643516941"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="wc-blocks-style-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks-style.css?ver=6.5.2-b-modified-1643516941"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="jquery-selectBox-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/plugins/yith-woocommerce-wishlist/assets/css/jquery.selectBox.css?ver=1.2.0-b-modified-1642491544"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="yith-wcwl-font-awesome-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/plugins/yith-woocommerce-wishlist/assets/css/font-awesome.css?ver=4.7.0-b-modified-1642491544"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="woocommerce_prettyPhoto_css-css"
      href="//cartsy.redq.io/furniture/wp-content/plugins/woocommerce/assets/css/prettyPhoto.css?ver=3.1.6"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="yith-wcwl-main-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/plugins/yith-woocommerce-wishlist/assets/css/style.css?ver=3.5.0-b-modified-1642491544"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="contact-form-7-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=5.5.4-b-modified-1643516919"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="woocommerce-layout-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/plugins/woocommerce/assets/css/woocommerce-layout.css?ver=6.1.1-b-modified-1643516941"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="woocommerce-smallscreen-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/plugins/woocommerce/assets/css/woocommerce-smallscreen.css?ver=6.1.1-b-modified-1643516941"
      type="text/css"
      media="only screen and (max-width: 768px)"
    />
    <link
      rel="stylesheet"
      id="woocommerce-general-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/plugins/woocommerce/assets/css/woocommerce.css?ver=6.1.1-b-modified-1643516941"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="query-modal-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/plugins/demo-switcher/assets/css/jquery.modal.min.css?ver=1635748457-b-modified-1635748457"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="switcher-style-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/plugins/demo-switcher/assets/css/switcher-style.css?ver=1635748457-b-modified-1635748457"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="cartsy_blocks-cgb-style-css-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/plugins/cartsy-helper/dist/blocks.style.build.css?ver=1.8.3-b-modified-1643447284"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="jquery.toast.min-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/plugins/cartsy-helper/assets/jquery.toast.min.css?ver=-b-modified-1601542468"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="cartsy-custom-style-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/themes/cartsy/assets/css/custom_script.css?ver=-b-modified-1623317657"
      type="text/css"
      media="all"
    />
    
    <link
      rel="stylesheet"
      id="swiper_css-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/themes/cartsy/assets/libs/swiper-bundle.min.css?ver=1.8.3-b-modified-1601542402"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="magnific-popup-css-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/themes/cartsy/assets/libs/magnific-popup.css?ver=1.8.3-b-modified-1601542402"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      as="style"
      id="ionicons-min-css-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/themes/cartsy/assets/libs/ionicons.min.css?ver=1.8.3-b-modified-1601547527"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="overlay-scrollbar-css-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/themes/cartsy/assets/libs/OverlayScrollbars.css?ver=1.8.3-b-modified-1609563311"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="cartsy-blocks-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/themes/cartsy/assets/css/blocks.css?ver=1.8.3-b-modified-1601542402"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="cartsy-style-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/themes/cartsy/style.css?b-modified=1643447084&amp;ver=5.9"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      id="cartsy-main-style-css"
      href="https://t5f2p5h8.stackpathcdn.com/wp-content/themes/cartsy/dist/cartsy-main-style.css?ver=1.8.3-b-modified-1643447084"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      as="style"
      id="cartsy-body-font-css"
      href="https://fonts.googleapis.com/css2?family=Open+Sans%3Aital%2Cwght%400%2C300%3B0%2C400%3B0%2C600%3B0%2C700%3B0%2C800%3B1%2C300%3B1%2C400%3B1%2C600%3B1%2C700%3B1%2C800&amp;display=swap&amp;ver=5.9"
      type="text/css"
      media="all"
    />
    <link
      rel="stylesheet"
      as="style"
      id="cartsy-special-font-css"
      href="https://fonts.googleapis.com/css2?family=Satisfy&amp;display=swap&amp;ver=5.9"
      type="text/css"
      media="all"
    />
    <script
      type="text/javascript"
      src="https://t5f2p5h8.stackpathcdn.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0"
      id="jquery-core-js"
    ></script>
    <script
      type="text/javascript"
      src="https://t5f2p5h8.stackpathcdn.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.3.2"
      id="jquery-migrate-js"
    ></script>
    <script
      type="text/javascript"
      src="https://t5f2p5h8.stackpathcdn.com/wp-includes/js/utils.min.js?ver=5.9"
      id="utils-js"
    ></script>
    <script
      type="text/javascript"
      src="https://t5f2p5h8.stackpathcdn.com/wp-includes/js/plupload/moxie.min.js?ver=1.3.5"
      id="moxiejs-js"
    ></script>
    <script
      type="text/javascript"
      src="https://t5f2p5h8.stackpathcdn.com/wp-includes/js/plupload/plupload.min.js?ver=2.1.9"
      id="plupload-js"
    ></script>
      <script
        type="text/javascript"
        src="https://t5f2p5h8.stackpathcdn.com/wp-includes/js/json2.min.js?ver=2015-05-03"
        id="json2-js"
      ></script>
    <link
      rel="https://api.w.org/"
      href="https://cartsy.redq.io/furniture/wp-json/"
    />
    <link
      rel="alternate"
      type="application/json"
      href="https://cartsy.redq.io/furniture/wp-json/wp/v2/pages/109"
    />
    <link
      rel="EditURI"
      type="application/rsd+xml"
      title="RSD"
      href="https://cartsy.redq.io/furniture/xmlrpc.php?rsd"
    />
    <link
      rel="wlwmanifest"
      type="application/wlwmanifest+xml"
      href="https://t5f2p5h8.stackpathcdn.com/wp-includes/wlwmanifest.xml"
    />
    <meta name="generator" content="WordPress 5.9" />
    <meta name="generator" content="WooCommerce 6.1.1" />
    <link rel="canonical" href="https://cartsy.redq.io/furniture/" />
    <link rel="shortlink" href="https://cartsy.redq.io/furniture/" />
    <link
      rel="alternate"
      type="application/json+oembed"
      href="https://cartsy.redq.io/furniture/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fcartsy.redq.io%2Ffurniture%2F"
    />
    <link
      rel="alternate"
      type="text/xml+oembed"
      href="https://cartsy.redq.io/furniture/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fcartsy.redq.io%2Ffurniture%2F&amp;format=xml"
    />
    </>

)
}